// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bowl struct {
	BowlID     string
	LocationID string
	CreatedAt  pgtype.Timestamp
	Descriptor string
}

type Location struct {
	LocationID string
	Geom       interface{}
	CreatedAt  pgtype.Timestamp
}
