// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID      string
	UserName    string
	PhoneNumber string
	CreatedAt   pgtype.Timestamp
}
