// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bathroom struct {
	BathroomID     string  `json:"bathroom_id"`
	Title          string  `json:"title"`
	Description    string  `json:"description"`
	LastUsed       *string `json:"last_used,omitempty"`
	LastUpdatedBy  *string `json:"last_updated_by,omitempty"`
	IsPublic       *bool   `json:"is_public,omitempty"`
	IsCustomerOnly *bool   `json:"is_customer_only,omitempty"`
	IsPayToUse     bool    `json:"is_pay_to_use"`
	VenueType      string  `json:"venue_type"`
	Flagged        bool    `json:"flagged"`
}

type BathroomInput struct {
	Title          string `json:"title"`
	Description    string `json:"description"`
	IsPublic       *bool  `json:"is_public,omitempty"`
	IsCustomerOnly *bool  `json:"is_customer_only,omitempty"`
	VenueType      string `json:"venue_type"`
}

type CreateBathroomMutationResponse struct {
	BathroomID string `json:"bathroom_id"`
}

type GeoLocation struct {
	Long float64 `json:"long"`
	Lat  float64 `json:"lat"`
}

type Location struct {
	LocationID string       `json:"location_id"`
	Point      *GeoLocation `json:"point"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type Token struct {
	TokenID   string `json:"token_id"`
	UserID    string `json:"user_id"`
	ExpiresAt string `json:"expires_at"`
}

type User struct {
	UserID      string `json:"user_id"`
	UserName    string `json:"user_name"`
	PhoneNumber string `json:"phone_number"`
}
