// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	UserName    string `json:"user_name"`
	PhoneNumber string `json:"phone_number"`
}

type User struct {
	UserID      string `json:"user_id"`
	UserName    string `json:"user_name"`
	PhoneNumber string `json:"phone_number"`
}
